apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql-chart.fullname" . }}
  labels:
    app: {{ include "postgresql-chart.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postgresql-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgresql-chart.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgresql.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresql.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgresql.database }}"
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: {{ include "postgresql-chart.fullname" . }}-pvc
